services:
  backend:
    env_file: .env.production
    environment:
      MINIO_ACCESS_KEY_FILE: /etc/secrets/minio_access_key.txt
      MINIO_SECRET_KEY_FILE: /etc/secrets/minio_secret_key.txt
      MONGODB_ACCESS_KEY_FILE: /etc/secrets/mongodb_access_key.txt
      MONGODB_SECRET_KEY_FILE: /etc/secrets/mongodb_secret_key.txt
      JWT_SECRET: /etc/secrets/jwt_secret
    secrets:
      - minio_access_key
      - minio_secret_key
      - mongodb_access_key
      - mongodb_secret_key
      - jwt_secret

  minio:
    env_file: .env.production
    environment:
      MINIO_ROOT_USER_FILE: /etc/secrets/minio_access_key.txt
      MINIO_ROOT_PASSWORD_FILE: /etc/secrets/minio_secret_key.txt
    secrets:
          - minio_access_key
          - minio_secret_key
  frontend:
    env_file: .env.production

secrets:
  minio_access_key: 
    file: ./secrets/minio-access-key.txt
  minio_secret_key: 
    file: ./secrets/minio-secret-key.txt
  mongodb_access_key: 
    file: ./secrets/mongodb-access-key.txt
  mongodb_secret_key: 
    file: ./secrets/mongodb-secret-key.txt
  jwt_secret: 
    file: ./secrets/jwt-secret.txt