services:
  backend:
    env_file: .env.production
    environment:
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_access_key
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_secret_key
      MONGODB_ACCESS_KEY_FILE: /run/secrets/mongodb_access_key
      MONGODB_SECRET_KEY_FILE: /run/secrets/mongodb_secret_key
      JWT_SECRET: /run/secrets/jwt_secret
    secrets:
      - minio_access_key
      - minio_secret_key
      - mongodb_access_key
      - mongodb_secret_key
      - jwt_secret

  minio:
    env_file: .env.production
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_secret_key
    secrets:
          - minio_access_key
          - minio_secret_key
  frontend:
    env_file: .env.production

secrets:
  minio_access_key: 
    file: ./secrets/minio_access_key.txt
  minio_secret_key: 
    file: ./secrets/minio_secret_key.txt
  mongodb_access_key: 
    file: ./secrets/mongodb_access_key.txt
  mongodb_secret_key: 
    file: ./secrets/mongodb_secret_key.txt
  jwt_secret: 
    file: ./secrets/jwt_secret.txt